### ISSUE TITLE
Talk title TBC for Harry Roberts on homepage but not schedule

### ISSUE THREAD

**Issue by tmcdb** [steersystems/beyond#12]
What I see: On the homepage Harry Roberts' talk has a title, but on the schedule page it doesn't.
What I expected to see: The homepage and schedule are consistent; either there is or there isn't a title

I know the long title was breaking the layout on the schedule but having title in one place and no title in the other is confusing for people looking for that title. 

(Feedback from a friend who asked where the CSS talk was in the schedule)

**Comment by alicemollon** [comment]
Thanks for pointing that out! It wasn't deliberate at all for there not to be the title on the schedule page, think it's just a mistake

**Comment by tmcdb** [comment]
:ok_hand: no problem

**Comment by Sambillingham** [comment]
Yeah Sam M changed the talk title on the homepage, not sure why. I was following the numbers doc with all the speaker info for data entry. I'm not sure the title is actually confirmed yet.

**Comment by Sambillingham** [comment]
I'll  make sure they're the same either way.

**Comment by Sambillingham** [comment]
Fixed in PR #11 :point_up:
