### ISSUE TITLE
Mailchimp sign up not working sporadically

### ISSUE THREAD

**Issue by tmcdb** [steersystems/beyond#2]
Submitting a new email address in the form _sometimes_ gives an error:

![beyond_error](https://cloud.githubusercontent.com/assets/3686887/9471434/28da37a0-4b48-11e5-9d94-f84f3d29f532.png)

**Comment by samjbmason** [comment]
Did this happen on the first time?

**Comment by Sambillingham** [comment]
No problems since initial issue and not reproducible.
