### ISSUE TITLE
Container Inconsistency across pages

### ISSUE THREAD

**Issue by Sambillingham** [steersystems/beyond#27]
What I see: container on header does not match with container on schedule
What I expect Content inside of containers to align 

<img width="1482" alt="screen shot 2015-09-22 at 15 39 51" src="https://cloud.githubusercontent.com/assets/2798285/10021547/621bd902-6140-11e5-9f0a-7e1febd9f1fa.png">

**Comment by samjbmason** [comment]
I think on desktop this should be the case but on mobile it doesnt make sense to have the logo push up against the ages and so I think we should keep the padding there

Desktop: Makes sense to remove padding :+1: 
![screen shot 2015-09-28 at 10 15 27](https://cloud.githubusercontent.com/assets/878503/10131674/e0b0bf34-65c9-11e5-8111-b57f45d3b850.png)

Mobile: Makes sense to leave in padding
![screen shot 2015-09-28 at 10 16 28](https://cloud.githubusercontent.com/assets/878503/10131696/05e1d400-65ca-11e5-9809-46e550b9e983.png)

**Comment by samjbmason** [comment]
This should fix this in #38

**Comment by Sambillingham** [comment]
:point_up: fixed in #50
