### ISSUE TITLE
Schedule button disappears on mobile

### ISSUE THREAD

**Issue by alicemollon** [steersystems/beyond#39]
What I see: 'Schedule' disappears from the home page navigation when down to the smallest mobile size.
What I expect to see: Both 'Tickets' and 'Schedule' in the home page navigation for all browser sizes.

Full version:
<img width="691" alt="screen shot 2015-09-28 at 11 33 06" src="https://cloud.githubusercontent.com/assets/6330185/10132064/d7aee32e-65d4-11e5-99ca-a28e61e30305.png">

Medium version:
<img width="755" alt="screen shot 2015-09-28 at 11 33 12" src="https://cloud.githubusercontent.com/assets/6330185/10132074/e4ac93c8-65d4-11e5-823b-6f6ce905c9c5.png">

Mobile version:
<img width="481" alt="screen shot 2015-09-28 at 11 33 19" src="https://cloud.githubusercontent.com/assets/6330185/10132079/eeda164a-65d4-11e5-863b-2e5752d033e4.png">

**Comment by samjbmason** [comment]
From the looks of the commit history this was added in as intended functionality https://github.com/steersystems/beyond/commit/6737ce5ba397b8c6d41865863f5fa9054d38358b

Its easy to bring back in but are we sure this is a bug?

**Comment by alicemollon** [comment]
It was supposed to disappear from the schedule page. Not sure why we'd want it to disappear from the home page?

**Comment by samjbmason** [comment]
I wonder if its worth leaving it in on both pages for consistency?

**Comment by alicemollon** [comment]
I don't think so. It might be fine on the iPhone 6, but on my phone for example, that nav takes up pretty much the whole screen. If it stays the same on both pages, it's hard to tell that you've moved to a different page.

**Comment by Sambillingham** [comment]
Good spot Alice, I accidentally caused that to happen when I made all the pages use the same header partial. The fix above puts it back to how we talked about so it only disappears on mobile on the schedule page.

**Comment by alicemollon** [comment]
:+1:
