### ISSUE TITLE
Update to README.md

### ISSUE THREAD

**Issue by samjbmason** [steersystems/beyond#42]
We should add into the readme a line talking about deploymenet and  whoever merges the Pull Request should then subsequently build and deploy the project

**Comment by Sambillingham** [comment]
- [ ] Some notes about the data files
- [ ] Gem install info

**Comment by Sambillingham** [comment]
[ ] Bower Components

**Comment by samjbmason** [comment]
I have a PR open at #103 that should deal with this issue

**Comment by Sambillingham** [comment]
Readme is in much better shape :) :tada:
