### ISSUE TITLE
Facebook Open graph image

### ISSUE THREAD

**Issue by samjbmason** [steersystems/beyond#43]
What I see: An error from open graph debugger saying the image link is not a url
![screen shot 2015-09-29 at 15 34 15](https://cloud.githubusercontent.com/assets/878503/10167235/91dc70f0-66bf-11e5-985c-80736fb12d37.png)

What I expect: No error and an image in the preview

Proposed fix: Change og:image:url to a fully qualified url rather than a relative path

**Comment by Sambillingham** [comment]
fixed in #44
