### ISSUE TITLE
IE SVG scaling 

### ISSUE THREAD

**Issue by Sambillingham** [steersystems/beyond#65]
What I see - Incorrect aspect ratios and size of svg images in Ie
What I Expect - images to look great across browsers

I used - [Screnshot Tool ](https://dev.modern.ie/tools/screenshots/#http://beyondconf.co) to grab some IE screenshots and noticed that IE is not placing nice with the SVG images. Came across this [fix] (https://gist.github.com/larrybotha/7881691)

See this screenshots for an example of the issue in IE11-
![screen shot 2015-10-12 at 13 25 59](https://cloud.githubusercontent.com/assets/2798285/10427855/d958f758-70e4-11e5-869c-84d19a8ae11f.png)

**Comment by Sambillingham** [comment]
@samjbmason I have started looking into this but It would be good if you could dive in too if you have time today. Not sure exactly which versions of IE this affects.

**Comment by samjbmason** [comment]
So this affects all versions of IE including 11

**Comment by Sambillingham** [comment]
11 was the only screenshot provided using the above tool so thats why I mentioned I was not sure, based on others with similar issues online I believe it is all versions of IE that support SVG - there is a note in caniuse about it [here](http://caniuse.com/#feat=svg).

**Comment by samjbmason** [comment]
I think there about 3-4 various issues affecting these images. 
Using `display:table` anything screws everything when images are involved in IE
Using correct viewbox attributes in our SVG's as IE while it does support again screws stuff
Being able to control svg images as background images does not have great support in IE

**Comment by Sambillingham** [comment]
Any more luck?

**Comment by samjbmason** [comment]
Yeah just commititn to the PR now

**Comment by Sambillingham** [comment]
Looks good. :+1:

**Comment by Sambillingham** [comment]
Fixed in #66 - still not perfect in IE but the SVG scaling is fixed. :+1:

**Comment by samjbmason** [comment]
What things are still breaking?

**Comment by Sambillingham** [comment]
Added it in a new issue #71 pretty generic for now
