### ISSUE TITLE
Ada's List being flagged as Advert in AdBlock

### ISSUE THREAD

**Issue by samjbmason** [steersystems/beyond#73]
What I see: An empty space where the logo should be

What I expect: To see the Ada's list logo.

Potential Solution: Stop using the word sponsors and maybe change ada list image name

**Comment by samjbmason** [comment]
This should be fixed in PR #104

**Comment by Sambillingham** [comment]
Interesting that combination causes Adblock to kick in, did you figure this out just through changing stuff or did you find any references online?

**Comment by samjbmason** [comment]
Yeah found it through changing stuff I assumed it was mostly the image file name but thought I would change the alt text juts in case. I did worry the url would cause an issue as well but thankfully it didnt.

**Comment by Sambillingham** [comment]
fixed in #104
