### ISSUE TITLE
Feature - Audio Player for speaker audio interviews

### ISSUE THREAD

**Issue by Sambillingham** [steersystems/beyond#74]
For audio Interviews/podcast crossovers it would be nice to have a custom player or post type for the blog similar if not almost identical to the one we have on the podcast site. currently we would need to link out to the podcast site or host it on soundcloud or something, both less than ideal

**Comment by samjbmason** [comment]
Yeah good idea, happy to build it out if you want

**Comment by Sambillingham** [comment]
This was build out in #80 :+1:
