### ISSUE TITLE
Compressing images with ImageOptim 

### ISSUE THREAD

**Issue by Sambillingham** [steersystems/beyond#85]
What I see: I've been using the mac imageOptim app to compress images every so often when I remember. 
What I expect: Should compress images whenever new images are added before ever being pushed.

Possible Fix: Use gulp task? just not sure when is appropriate, maybe a task that watches for changes in the image folder?

**Comment by samjbmason** [comment]
I have created a branch for this I imagine it does a similar thing to what @Sambillingham setup before just reimplemented
